language: python
python:
    - "2.6"
    - "2.7"

install:
    - sudo apt-get install beanstalkd
    - pip install -r .travis-requirements.txt --use-mirrors
script: nosetests -c .nose.cfg

branches:
    only:
        - master
